name: "ASP.NET Core CI/CD Pipeline"

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

  check-code-format:
    uses: ./.github/workflows/reusable/shared-methods.yml#check-code-format
    with:
      language: 'dotnet'

  scan-security-vulnerabilities:
    uses: ./.github/workflows/reusable/shared-methods.yml#scan-security-vulnerabilities
    with:
      language: 'dotnet'

  build-artifact:
    runs-on: ubuntu-latest
    needs: [build, check-code-format, scan-security-vulnerabilities]
    steps:
      - name: Build Release Artifact
        run: dotnet publish -c Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aspnetcore-release-artifact
          path: ./publish

  generate-coverage:
    uses: ./.github/workflows/reusable/shared-methods.yml#generate-coverage
    with:
      language: 'dotnet'

  upload-coverage-report:
    uses: ./.github/workflows/reusable/shared-methods.yml#upload-coverage-report
    with:
      language: 'dotnet'

  clean-up:
    uses: ./.github/workflows/reusable/shared-methods.yml#clean-up
    with:
      language: 'dotnet'
