services:
  loki:
    image: grafana/loki:3.3.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/cache:/loki/cache
      - ./loki-data/wal:/loki/wal
      - ./loki-config.yml:/etc/loki/loki-config.yml # Se mapea directamente el archivo de configuración
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - grafana-loki-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.3.0
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana-loki-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    networks:
      - grafana-loki-net
    restart: unless-stopped

volumes:
  grafana-storage: {}

networks:
  grafana-loki-net:
    driver: bridge
