auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  storage_config:
    boltdb_shipper:
      active_index_directory: /tmp/loki/index
      shared_store: filesystem
      cache_location: /tmp/loki/boltdb-cache
    filesystem:
      directory: /tmp/loki/chunks

  ring:
    kvstore:
      store: inmemory

query_range:
  align_queries_with_step: true
  max_retries: 5

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 10m

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
