name: "Analyze Logs"

on:
  workflow_call:
    inputs:
      log-files:
        description: 'Patrón de archivos de logs a analizar'
        required: true
        type: string
      analysis-type:
        description: 'Tipo de análisis a realizar: error, improvement, or both'
        required: true
        type: string

jobs:
  analyze-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze Logs with OpenAI
        run: |
          echo "Analyzing logs of type: ${{ inputs.analysis-type }}"
          python scripts/analyze_logs.py --log-files "${{ inputs.log-files }}" --analysis-type "${{ inputs.analysis-type }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
