name: "Check Code Format"

on:
  workflow_call:
    inputs:
      language:
        description: 'The programming language for the code format check'
        required: true
        type: string
      project-path:
        description: 'La ruta del proyecto donde se encuentra el código Java'
        required: false
        type: string
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: false
        type: string
      node-version:
        description: 'La versión de Node.js para usar en este pipeline'
        required: false
        type: string
      go-version:
        description: 'La versión de Go para usar en este pipeline'
        required: false
        type: string
      python-version:
        description: 'La versión de Python para usar en este pipeline'
        required: false
        type: string
      java-version:
        description: 'La versión de Java para usar en este pipeline'
        required: false
        type: string

jobs:
  check-code-format:
    runs-on: ubuntu-latest
    steps:
      # Realizar el checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar .NET si el lenguaje es 'dotnet' y hay una versión especificada
      - name: Set up .NET Core
        if: ${{ inputs.language == 'dotnet' && inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "${{ inputs.dotnet-version }}"

      # Instalar Node.js si el lenguaje es 'node' y hay una versión especificada
      - name: Set up Node.js
        if: ${{ inputs.language == 'node' && inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.node-version }}"

      # Instalar Black si el lenguaje es Python
      - name: Install Black for Python
        if: ${{ inputs.language == 'python' }}
        run: pip install black

      # Ejecutar el formateo de código basado en el lenguaje
      - name: Run Code Formatter
        run: |
          if [ "${{ inputs.language }}" == "go" ]; then
            echo "Running Go formatter"
            gofmt -l .
          elif [ "${{ inputs.language }}" == "node" ]; then
            echo "Running Prettier for Node.js"
            npx prettier --check .
          elif [ "${{ inputs.language }}" == "python" ]; then
            echo "Installing and running Black for Python"
            black --check . || true 
          elif [ "${{ inputs.language }}" == "java" ]; then
            echo "Running Gradle formatter for Java"
            if [ -f "./gradlew" ]; then
              chmod +x ./gradlew
              ./gradlew -p ${{ inputs.project-path }} format || true
            else
              echo "Gradle wrapper (gradlew) not found. Skipping Java code format check."
            fi
          elif [ "${{ inputs.language }}" == "dotnet" ]; then
            version=$(echo "${{ inputs.dotnet-version }}" | cut -d'.' -f1)
            if [ "$version" -lt 3 ]; then
              echo "Skipping dotnet format: version is less than 3. Your version: ${{ inputs.dotnet-version }}"
            else
              echo "Running dotnet format"
              dotnet format
            fi
          fi
