name: "Clean Up"

on:
  workflow_call:
    inputs:
      language:
        description: 'The programming language for the clean-up process'
        required: true
        type: string
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: false
        type: string
      go-version:
        description: 'La versión de Go para usar en este pipeline'
        required: false
        type: string
      python-version:
        description: 'La versión de Python para usar en este pipeline'
        required: false
        type: string
      java-version:
        description: 'La versión de Java para usar en este pipeline'
        required: false
        type: string

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      # Realizar el checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar .NET si el lenguaje es 'dotnet' y hay una versión especificada
      - name: Set up .NET Core
        if: ${{ inputs.language == 'dotnet' && inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "${{ inputs.dotnet-version }}"

      # Instalar Go si el lenguaje es 'go' y hay una versión especificada
      - name: Set up Go
        if: ${{ inputs.language == 'go' && inputs.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      # Instalar Python si el lenguaje es 'python' y hay una versión especificada
      - name: Set up Python
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"

      # Proceso de limpieza basado en el lenguaje
      - name: Clean Up Build Artifacts
        run: |
          if [ "${{ inputs.language }}" == "go" ]; then
            echo "Cleaning up Go build artifacts"
            rm -rf ./bin ./build
          elif [ "${{ inputs.language }}" == "node" ]; then
            echo "Cleaning up Node.js build artifacts"
            rm -rf ./dist ./build
          elif [ "${{ inputs.language }}" == "python" ]; then
            echo "Cleaning up Python build artifacts"
            rm -rf ./dist ./build ./__pycache__ ./*.egg-info
          elif [ "${{ inputs.language }}" == "java" ]; then
            echo "Cleaning up Java build artifacts"
            find . -name "pom.xml" ! -path "*/test/*" ! -path "*/src/test/*" | while read -r pom_path; do
              project_dir=$(dirname "$pom_path")
              echo "Running Maven clean in $project_dir"
              if [ -f "$project_dir/mvnw" ]; then
                (cd "$project_dir" && ./mvnw clean)
              else
                (cd "$project_dir" && mvn clean)
              fi
            done
          elif [ "${{ inputs.language }}" == "dotnet" ]; then
            echo "Cleaning up .NET build artifacts"
            rm -rf ./publish ./TestResults
          fi
