name: "Analyze and Create JIRA Tickets"

on:
  workflow_call:
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME:
        description: "Azure Storage Account Name"
        required: true
      AZURE_STORAGE_ACCOUNT_KEY:
        description: "Azure Storage Account Key"
        required: true
      OPENAI_API_KEY:
        description: "OpenAI API Key"
        required: true
      JIRA_CLOUD_API_TOKEN:
        description: "Jira Cloud API Token"
        required: true
      JIRA_CLOUD_USERNAME:
        description: "Jira Cloud Username"
        required: true
    inputs:
      project-name:
        description: "The name of the GitHub repository"
        required: true
        type: string
      run-id:
        description: "The ID of the current GitHub run"
        required: true
        type: string
      report-language:
        description: "Language for the summary report (default: English)"
        required: false
        type: string
        default: "English"
      log-type:
        description: "Type of logs to analyze (e.g., failure, success)"
        required: true
        type: string
      repo:
        description: "The name of the GitHub repository (owner/repo)"
        required: true
        type: string
      jira-project-key:
        description: "Reference to the Jira Project"
        required: true
        type: string
      jira-url:
        description: "URL of the Jira Cloud instance"
        required: true
        type: string

jobs:
  analyze-and-create:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install jira requests openai
          python -c "import openai; print('OpenAI library installed successfully')"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Download your unified script
        run: |
          git clone https://github.com/guillipa1993/devops-pipelines-ci-cd.git
          mkdir -p scripts
          cp devops-pipelines-ci-cd/scripts/unified_analyze_and_create.py scripts/
          if [ ! -f "scripts/unified_analyze_and_create.py" ]; then
            echo "ERROR: No unified script found." >&2
            exit 1
          fi
          echo "Found unified_analyze_and_create.py script."

      - name: Download All Logs Matching Pattern
        run: |
          # Ajusta el patrón según necesites. Por ejemplo:
          REPO_NAME="${{ inputs.project-name }}"
          RUN_ID="${{ inputs.run-id }}"
          LOG_PREFIX="${REPO_NAME}-${RUN_ID}-"

          mkdir -p $GITHUB_WORKSPACE/logs

          # List all blobs that match "*<prefix>*.log" (o la extensión real que quieras)
          az storage blob list \
            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
            --container-name logs \
            --query "[].{name:name}" -o tsv | grep "${LOG_PREFIX}" | grep '\.log$' > matching_blobs.txt || true

          if [ ! -s matching_blobs.txt ]; then
            echo "No .log files found for pattern: ${LOG_PREFIX}*.log"
            exit 0  # -> si no hay logs, no pasa nada
          fi

          while IFS= read -r blob_name; do
            echo "Downloading $blob_name"
            az storage blob download \
              --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
              --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
              --container-name logs \
              --name "$blob_name" \
              --file "$GITHUB_WORKSPACE/logs/$(basename $blob_name)"
          done < matching_blobs.txt

          echo "Logs downloaded:"
          ls -la $GITHUB_WORKSPACE/logs
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

      - name: Run unified script to Analyze + Create JIRA Tickets
        run: |
          python scripts/unified_analyze_and_create.py \
            --jira-url "${{ inputs.jira-url }}" \
            --jira-project-key "${{ inputs.jira-project-key }}" \
            --log-dir "$GITHUB_WORKSPACE/logs" \
            --log-type "${{ inputs.log-type }}" \
            --report-language "${{ inputs.report-language }}" \
            --project-name "${{ inputs.project-name }}" \
            --run-id "${{ inputs.run-id }}" \
            --repo "${{ inputs.repo }}"
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_CLOUD_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_CLOUD_USERNAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
