name: "ASP.NET Core CI/CD Pipeline"

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: true
        type: string
      language:
        description: 'El lenguaje de programación para usar en este pipeline'
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal

  check-code-format:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check Code Format
        uses: ./.github/workflows/check-code-format.yml
        with:
          language: ${{ inputs.language }}

  scan-security:
    runs-on: ubuntu-latest
    needs: check-code-format
    steps:
      - name: Scan Security Vulnerabilities
        uses: ./.github/workflows/scan-security-vulnerabilities.yml
        with:
          language: ${{ inputs.language }}

  build-artifact:
    runs-on: ubuntu-latest
    needs: scan-security
    steps:
      - name: Build Artifact
        uses: ./.github/workflows/build-artifact.yml
        with:
          language: ${{ inputs.language }}

  generate-coverage:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - name: Generate Coverage
        uses: ./.github/workflows/generate-coverage.yml
        with:
          language: ${{ inputs.language }}

  upload-coverage:
    runs-on: ubuntu-latest
    needs: generate-coverage
    steps:
      - name: Upload Coverage Report
        uses: ./.github/workflows/upload-coverage-report.yml
        with:
          language: ${{ inputs.language }}

  clean-up:
    runs-on: ubuntu-latest
    needs: upload-coverage
    steps:
      - name: Clean Up
        uses: ./.github/workflows/clean-up.yml
        with:
          language: ${{ inputs.language }}
