name: "ASP.NET Core CI/CD Pipeline"

on:
  workflow_call:
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME:
        description: 'Azure Storage Account Name'
        required: true
      AZURE_STORAGE_ACCOUNT_KEY:
        description: 'Azure Storage Account Key'
        required: true
      OPENAI_API_KEY:
        description: 'OpenAI API Key'
        required: true
    inputs:
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: true
        type: string
      language:
        description: 'El lenguaje de programación para usar en este pipeline'
        required: true
        type: string
      project-path:
        description: 'La ruta del proyecto donde se encuentran los archivos .csproj'
        required: true
        type: string
      build-command:
        description: "Comando personalizado para construir el proyecto"
        required: false
        type: string
      build-configuration:
        description: 'Configuración de build (Debug o Release)'
        required: true
        type: string
      additional-install-commands:
        description: 'Comandos adicionales para instalar dependencias antes de construir'
        required: false
        type: string
      report-language:
        description: 'Idioma en el que se generará el informe (por ejemplo: English, Spanish, French, German, Italian). Por defecto, se utiliza inglés si no se especifica.'
        required: false
        type: string
      run-check-code-format:
        description: 'Ejecutar la verificación del formato del código'
        required: true
        type: boolean
      run-code-analysis:
        description: 'Ejecutar el análisis de código'
        required: true
        type: boolean
      run-lint:
        description: 'Ejecutar Lint'
        required: true
        type: boolean
      environment-variables:
        description: 'Variables de entorno para configurar en el pipeline (formato: "VAR1=value1, VAR2=value2")'
        required: false
        type: string

jobs:
  # Job principal para construir el proyecto
  ci_pipeline:
    runs-on: ubuntu-24.04
    outputs:
      error-detected: ${{ steps.analyze.outputs.error-detected || 'success' }}
    steps:
      - name: Initialize error-detected
        run: echo "error-detected=success" >> $GITHUB_ENV

      - name: Debug OS Version
        run: lsb_release -a || cat /etc/os-release
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Set Azure Environment Variables
        run: |
          echo "Setting Azure environment variables..."
          echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV
      
      - name: Set OpenAI API Key
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      
      - name: Verify Secrets
        run: |
          echo "Azure Account Name: ${AZURE_STORAGE_ACCOUNT_NAME}"
          echo "Azure Account Key: ${AZURE_STORAGE_ACCOUNT_KEY}"
          echo "OpenAI API Key: ${OPENAI_API_KEY}"

      - name: Set Environment Variables
        if: ${{ inputs.environment-variables }}
        run: |
          echo "Setting environment variables"
          IFS=',' read -ra VARS <<< "${{ inputs.environment-variables }}"
          for VAR in "${VARS[@]}"; do
            echo "Setting $VAR"
            echo "$VAR" >> $GITHUB_ENV
          done
      
      - name: Install additional dependencies
        if: ${{ inputs.additional-install-commands }}
        run: |
          echo "Running additional install commands"
          mkdir -p "${GITHUB_WORKSPACE}/logs"
          repo_name=$(basename "${{ github.repository }}")
          ${{ inputs.additional-install-commands }} 2>&1 | tee "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-additional_install.log"
          if [ ! -f "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-additional_install.log" ]; then
            echo "ERROR : Log file for additional dependencies installation was not created!" >&2
            exit 1
          else
            echo "SUCCESS : Log file for additional dependencies installation was created!" >&2
          fi

      - name: Install dependencies and Save Logs
        run: |
          echo "Installing dependencies with increased timeout and fallback to PyPI"
          mkdir -p "${GITHUB_WORKSPACE}/logs"

          # Variables dinámicas
          repo_name=$(basename "${GITHUB_REPOSITORY}")
          log_file="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-dependencies.log"
      
          dotnet restore ${{ inputs.project-path }} 2>&1 | tee "$log_file"

          # Verificación de creación del log
          if [ ! -f "$log_file" ]; then
            echo "ERROR: Log file $log_file was not created!" >&2
            exit 1
          else
            echo "SUCCESS: Log file $log_file was created!" >&2
          fi

      - name: Build All .NET Projects
        id: build
        run: |
          echo "Starting the build process for all .NET projects"
          mkdir -p "${GITHUB_WORKSPACE}/logs"
      
          # Variables dinámicas
          repo_name="$${{ github.repository }}"  # Asegúrate de que inputs.project-name sea modular-todo-app
          consolidated_log="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-consolidated-build.log"
          touch "$consolidated_log"
      
          # Buscar todos los archivos .csproj dentro del project-path
          find "${{ inputs.project-path }}" -type f -name "*.csproj" | while read -r project_file; do
            project_name=$(basename "$project_file")
            project_log="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-${project_name}.log"
            
            echo "Building project: $project_name"
            echo "Log file: $project_log"
      
            # Construir el proyecto
            dotnet build "$project_file" --configuration "${{ inputs.build-configuration }}" 2>&1 | tee "$project_log"
            build_status=${PIPESTATUS[0]}
      
            # Consolidar el log
            echo "======== Log for $project_name ========" >> "$consolidated_log"
            cat "$project_log" >> "$consolidated_log"
            echo "" >> "$consolidated_log"
      
            # Verificar errores en el build actual
            if [ $build_status -ne 0 ]; then
              echo "ERROR: Build failed for project $project_name. See logs for details."
            fi
          done
      
          # Verificar si hay errores en el log consolidado
          if grep -qiE "(ERROR|Build FAILED)" "$consolidated_log"; then
              echo "ERROR: Build logs contain errors. Check the consolidated log for details."
              exit 1
          else
              echo "SUCCESS: All projects built successfully!"
          fi        
      
      - name: Move build artifacts to workspace
        run: |
          echo "GITHUB_WORKSPACE is: ${GITHUB_WORKSPACE}"
          echo "Searching for build artifacts..."
          ARTIFACT_FILES=$(find "${GITHUB_WORKSPACE}/bin/Release/" -type f -name "*.dll" -o -name "*.nupkg")
          if [ -n "$ARTIFACT_FILES" ]; then
            echo "Build artifacts found:"
            echo "$ARTIFACT_FILES"
            mkdir -p "${GITHUB_WORKSPACE}/dist"
            for FILE in $ARTIFACT_FILES; do
              cp "$FILE" "${GITHUB_WORKSPACE}/dist/"
            done
            if [ "$(ls -A ${GITHUB_WORKSPACE}/dist)" ]; then
              echo "SUCCESS: Build artifacts moved to dist directory."
            else
              echo "ERROR: Failed to move build artifacts." >&2
              exit 1
            fi
          else
            echo "ERROR: No build artifacts found!"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: steps.move-wheel.outputs.file-exists == 'true'
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_id }}
          path: ${{ github.workspace }}/dist/**
          if-no-files-found: ignore
        
      - name: Debug Logs Directory
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing contents of the current directory:"
          ls -la
          echo "Listing contents of the GITHUB_WORKSPACE directory:"
          ls -la $GITHUB_WORKSPACE
          echo "Checking if the logs directory exists in the workspace:"
          if [ -d "$GITHUB_WORKSPACE/logs" ]; then
            echo "Logs directory exists in the workspace."
            ls -la $GITHUB_WORKSPACE/logs
          else
            echo "ERROR: Logs directory does not exist in the workspace!"
          fi      
     
      # Paso para verificar si el nombre de la cuenta de almacenamiento está configurado
      - name: Debug Storage Account Name
        if: always()
        run: |
          echo "Checking if AZURE_STORAGE_ACCOUNT_NAME is set..."
          if [ -z "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" ]; then
            echo "ERROR: AZURE_STORAGE_ACCOUNT_NAME is not set." >&2
            exit 1
          else
            echo "Account Name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
          fi
      
      - name: Verify Logs Directory
        if: always()
        run: |
          if [ -d "$GITHUB_WORKSPACE/logs" ] && [ "$(ls -A $GITHUB_WORKSPACE/logs)" ]; then
            echo "Logs directory exists and contains files:"
            ls -la $GITHUB_WORKSPACE/logs
          else
            echo "ERROR: Logs directory is empty or does not exist!" >&2
            exit 1
          fi

      # Paso para subir los logs al contenedor de Azure Storage
      - name: Upload Logs to Azure Storage
        if: always()
        run: |
          if [ -d "$GITHUB_WORKSPACE/logs" ]; then
            for log in $GITHUB_WORKSPACE/logs/*.log; do
              echo "Uploading $log to Azure Storage..."
              az storage blob upload --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
                                    --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
                                    --container-name logs \
                                    --file "$log" \
                                    --name "$(basename $log)" \
                                    --overwrite
            done
          else
            echo "ERROR: Logs directory does not exist. Skipping upload." >&2
            exit 1
          fi

      - name: Debug analyze_failed_logs input
        if: always()
        run: |
          echo "Error-detected from ci_pipeline: ${{ needs.ci_pipeline.outputs.error-detected }}"
          echo "Nueva variable input error-detected : ${{ inputs.error-detected }}"
      
      - name: Verify and analyze logs for errors
        id: analyze
        if: always()
        run: |
          echo "Analyzing logs for errors..."
          repo_name=$(basename "${{ github.repository }}")
          log_file="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-build.log"

          if [ -f "$log_file" ]; then
            if grep -qi "error" "$log_file"; then
              echo "Errors found in logs."
              echo "error-detected=failure" >> $GITHUB_ENV
              echo "error-detected=failure" >> $GITHUB_OUTPUT
            else
              echo "No errors found."
              echo "error-detected=success" >> $GITHUB_ENV
              echo "error-detected=success" >> $GITHUB_OUTPUT
            fi
          else
            echo "ERROR: Build log file not found!" >&2
            echo "error-detected=failure" >> $GITHUB_ENV
            echo "error-detected=failure" >> $GITHUB_OUTPUT
          fi

      - name: Debug error-detected
        run: |
          echo "error-detected (from ENV): ${{ env.error-detected }}"
          echo "error-detected (from OUTPUT): ${{ steps.analyze.outputs.error-detected || 'not set' }}"
  
      - name: Debug final error-detected
        if: always()
        run: |
          echo "Final error-detected value (from ENV): ${{ inputs.error-detected }} || 'not set' }}"
          echo "Final error-detected value (from OUTPUT): ${{ steps.analyze.outputs.error-detected || 'not set' }}"
        
  # Job separado para formatear código y recopilar logs
  check-code-format:
    name: Check Code Format
    needs: ci_pipeline
    if: ${{ inputs.run-check-code-format }}
    uses: ./.github/workflows/check-code-format.yml
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
    with:
      language: ${{ inputs.language }}
      dotnet-version: ${{ inputs.dotnet-version }}

  # Job separado para análisis de código
  code-analysis:
    name: Code Analysis
    needs: ci_pipeline
    if: ${{ inputs.run-code-analysis }}
    uses: ./.github/workflows/scan-security-vulnerabilities.yml
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
    with:
      language: ${{ inputs.language }}
      dotnet-version: ${{ inputs.dotnet-version }} 
      project-path: ${{ inputs.project-path }}

  # Job separado para ejecutar YAML Lint
  dotnet-lint:
    needs: ci_pipeline
    if: ${{ inputs.run-lint }}
    uses: ./.github/workflows/lint.yml
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
    with:
      language: ${{ inputs.language }}

  analyze_logs:
    needs: [ci_pipeline, check-code-format, code-analysis, dotnet-lint]
    if: always()
    uses: ./.github/workflows/analyze-logs.yml
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    with:
      project-name: ${{ github.repository }}
      run-id: ${{ github.run_id }}
      log-type: ${{ needs.ci_pipeline.outputs.error-detected }}

  summarize_and_create_ticket:
    name: Summarize and Create Ticket
    needs: [ci_pipeline,analyze_logs]
    if: always()
    uses: ./.github/workflows/summarize-and-create-ticket.yml
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    with:
      project-name: ${{ github.event.repository.name }}
      run-id: ${{ github.run_id }}
      report-language: ${{ inputs.report-language }}
      log-type: ${{ needs.ci_pipeline.outputs.error-detected }}
      repo: ${{ github.repository }}
