name: "Java - CI Pipeline"

on:
  workflow_call:
    inputs:
      java-version:
        description: 'La versión de Java para usar en este pipeline'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java-version }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  notify:
    uses: ./.github/workflows/reusable/shared-methods.yml#send-notification