name: "Lint Code"

on:
  workflow_call:
    inputs:
      language:
        description: 'The programming language for linting'
        required: true
        type: string
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: false
        type: string

jobs:
 # Job para ejecutar Super-Linter solo para lenguajes soportados
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Ejecutar Super-Linter solo si el lenguaje es compatible
      - name: Run Super-Linter
        if: ${{ inputs.language == 'yaml' || inputs.language == 'python' || inputs.language == 'node' || inputs.language == 'markdown' }}
        uses: github/super-linter@v4
        with:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: .github/linters

      # Ejecutar el linter de .NET si es necesario
      - name: Run .NET Linter
        if: ${{ inputs.language == 'dotnet' }}
        run: |
          version=$(echo "${{ inputs.dotnet-version }}" | cut -d'.' -f1)
          if [ "$version" -lt 3 ]; then
            echo "Skipping dotnet format: version is less than 3. Using 'dotnet build' instead."
            dotnet build --nologo --no-restore --verbosity:minimal
          else
            echo "Running .NET linter (dotnet format)"
            dotnet format --verify-no-changes
          fi
