name: "Lint Code"

on:
  workflow_call:
    secrets:
      AZURE_STORAGE_ACCOUNT_NAME:
        description: 'Azure Storage Account Name'
        required: true
      AZURE_STORAGE_ACCOUNT_KEY:
        description: 'Azure Storage Account Key'
        required: true
    inputs:
      language:
        description: 'The programming language for linting'
        required: true
        type: string
      node-version:
        description: 'La versión de Node para usar en este pipeline'
        required: false
        type: string
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: false
        type: string
      go-version:
        description: 'La versión de Go para usar en este pipeline'
        required: false
        type: string
      python-version:
        description: 'La versión de Python para usar en este pipeline'
        required: false
        type: string
      java-version:
        description: 'La versión de Java para usar en este pipeline'
        required: false
        type: string

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Ensure logs directory exists
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/logs"
          echo "Logs directory created: ${GITHUB_WORKSPACE}/logs"

      # Ejecutar el linter de Go y otras verificaciones
      - name: Run Go Linter and Static Checks
        if: ${{ inputs.language == 'go' && inputs.go-version }}
        run: |
          echo "Running Go Linter and Static Checks" | tee "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-go-linter.log"
          mkdir -p "${GITHUB_WORKSPACE}/logs"
          log_file="${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-go-linter.log"

          # Formateo con gofmt
          echo "Running gofmt..." | tee -a "$log_file"
          gofmt -l . 2>&1 | tee -a "$log_file"

          # Análisis estático con go vet
          echo "Running go vet..." | tee -a "$log_file"
          go vet ./... 2>&1 | tee -a "$log_file"

          # Análisis de estilo con golint
          echo "Running golint..." | tee -a "$log_file"
          if ! command -v golint &> /dev/null; then
            echo "Installing golint..." | tee -a "$log_file"
            go install golang.org/x/lint/golint@latest
          fi
          golint ./... 2>&1 | tee -a "$log_file"

          # Verificaciones avanzadas con staticcheck
          echo "Running staticcheck..." | tee -a "$log_file"
          if ! command -v staticcheck &> /dev/null; then
            echo "Installing staticcheck..." | tee -a "$log_file"
            go install honnef.co/go/tools/cmd/staticcheck@latest
          fi
          staticcheck ./... 2>&1 | tee -a "$log_file"

          # Verificar si hubo errores en el log
          if grep -q "ERROR" "$log_file"; then
            echo "Errors detected during Go linting and static checks." >&2
            exit 1
          fi    

      - name: Set up Node.js
        if: ${{ inputs.language == 'node' && inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        if: ${{ inputs.language == 'node' }}
        run: |
          echo "Installing Node.js dependencies"
          mkdir -p "${GITHUB_WORKSPACE}/logs"
          log_file="${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-node-dependencies.log"
          npm ci 2>&1 | tee "$log_file"

          if [ ! -f "$log_file" ]; then
            echo "ERROR: Log file $log_file was not created!" >&2
            exit 1
          else
            echo "SUCCESS: Log file $log_file was created!" >&2
          fi

      # Ejecutar el linter de Node.js
      - name: Run Node.js Linter
        if: ${{ inputs.language == 'node' }}
        run: |
          echo "Running Node.js linter"
          mkdir -p "${GITHUB_WORKSPACE}/logs"
          log_file="${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-node-linter.log"
          
          # Verificar si existe un script de linting en package.json
          if grep -q '"lint":' package.json; then
            echo "Found 'lint' script in package.json. Running 'npm run lint'." | tee -a "$log_file"
            npm run lint 2>&1 | tee -a "$log_file"
          else
            echo "No 'lint' script found in package.json. Skipping linting step." | tee -a "$log_file"
          fi

          # Verificar si hubo errores durante el linting
          if grep -qi "error" "$log_file"; then
            echo "ERROR: Found 'error' in linting logs!" >&2
            exit 1
          fi

          # Confirmar la creación del log
          if [ ! -f "$log_file" ]; then
            echo "ERROR: Log file $log_file was not created!" >&2
            exit 1
          else
            echo "SUCCESS: Log file $log_file was created!" >&2
          fi

      # Ejecutar el linter de Python
      - name: Set up Python
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"
      
      - name: Install Python Linter
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        run: |
          pip install flake8
      
      - name: Run Python Linter and Save Results
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        run: |
          echo "Running Python linter (flake8)" | tee "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-python-linter.log"
          flake8 . --ignore=E501,E203,E228,E221,E302,E303,W503 --output-file="${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-python-linter.log" || true

      # Ejecutar el linter de .NET
      - name: Run .NET Linter
        if: ${{ inputs.language == 'dotnet' }}
        run: |
          if [ -z "${{ inputs.dotnet-version }}" ]; then
            echo "No .NET version provided. Skipping .NET format check."
          else
            version=$(echo "${{ inputs.dotnet-version }}" | cut -d'.' -f1)
            if [ "$version" -lt 3 ]; then
              echo "Skipping .NET format: version is less than 3. Using 'dotnet build' instead."
              dotnet build --nologo --no-restore --verbosity=minimal 2>&1 | tee -a "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-dotnet-linter.log" || true
            else
              echo "Running .NET linter (dotnet format)"
              dotnet format --verify-no-changes 2>&1 | tee -a "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-dotnet-linter.log" || true
            fi
          fi
        continue-on-error: true 

      # Ejecutar el linter de Java
      - name: Set up Java
        if: ${{ inputs.language == 'java' && inputs.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: "${{ inputs.java-version }}"
          distribution: 'temurin'

      - name: Run Java Checkstyle
        if: ${{ inputs.language == 'java' }}
        run: |
          echo "Running Checkstyle for Java" | tee "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-java-linter.log"
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew checkstyleMain 2>&1 | tee -a "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-java-linter.log" || true
          else
            echo "Gradle wrapper not found. Skipping Java linter." | tee -a "${GITHUB_WORKSPACE}/logs/${{ github.event.repository.name }}-${{ github.run_id }}-java-linter.log"
          fi        
        continue-on-error: true
      
      - name: Upload Logs to Azure Storage
        run: |
          if [ -d "$GITHUB_WORKSPACE/logs" ]; then
            for log in $GITHUB_WORKSPACE/logs/*.log; do
              echo "Uploading $log to Azure Storage..."
              az storage blob upload --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
                                    --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
                                    --container-name logs \
                                    --file "$log" \
                                    --name "$(basename $log)" \
                                    --overwrite
            done
          else
            echo "ERROR: Logs directory does not exist. Skipping upload." >&2
            exit 1
          fi