name: "Lint Code"

on:
  workflow_call:
    inputs:
      language:
        description: 'The programming language for linting'
        required: true
        type: string
      dotnet-version:
        description: 'La versión de .NET para usar en este pipeline'
        required: false
        type: string
      go-version:
        description: 'La versión de Go para usar en este pipeline'
        required: false
        type: string
      python-version:
        description: 'La versión de Python para usar en este pipeline'
        required: false
        type: string
      java-version:
        description: 'La versión de Java para usar en este pipeline'
        required: false
        type: string

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Ejecutar el linter de Go
      - name: Run Go Linter
        if: ${{ inputs.language == 'go' && inputs.go-version }}
        run: |
          echo "Running Go formatter"
          gofmt -l .

      # Ejecutar el linter de Node.js
      - name: Run Node.js Linter
        if: ${{ inputs.language == 'node' }}
        run: |
          echo "Running Prettier for Node.js"
          npm install --global prettier
          prettier --check .

      # Ejecutar el linter de Python
      - name: Set up Python
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"
      
      - name: Install Python Linter
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        run: |
          pip install flake8
      
      - name: Run Python Linter and Save Results
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        run: |
          echo "Running Python linter (flake8) and saving results"
          flake8 . > flake8_report.txt || true

      - name: Analyze flake8 Results
        if: ${{ inputs.language == 'python' && inputs.python-version }}
        run: |
          echo "Analyzing flake8 results"
          if [ -s flake8_report.txt ]; then
            echo "Found issues in flake8 report:"
            cat flake8_report.txt
            # Opcionalmente, contar el número de problemas
            issue_count=$(wc -l < flake8_report.txt)
            echo "$issue_count issues found."
            # Agregar una condición en función del número de problemas
            if [ "$issue_count" -gt 100 ]; then
              echo "Too many issues ($issue_count) found in the codebase. Please review."
            fi
          else
            echo "No issues found by flake8."
          fi
        continue-on-error: true 

      # Ejecutar el linter de .NET
      - name: Run .NET Linter
        if: ${{ inputs.language == 'dotnet' }}
        run: |
          if [ -z "${{ inputs.dotnet-version }}" ]; then
            echo "No .NET version provided. Skipping .NET format check."
          else
            version=$(echo "${{ inputs.dotnet-version }}" | cut -d'.' -f1)
            if [ "$version" -lt 3 ]; then
              echo "Skipping .NET format: version is less than 3. Using 'dotnet build' instead."
              dotnet build --nologo --no-restore --verbosity=minimal
            else
              echo "Running .NET linter (dotnet format)"
              dotnet format --verify-no-changes
            fi
          fi
        continue-on-error: true 

      # Ejecutar el linter de Java
      - name: Set up Java
        if: ${{ inputs.language == 'java' && inputs.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: "${{ inputs.java-version }}"
          distribution: 'temurin'

      - name: Run Java Checkstyle
        if: ${{ inputs.language == 'java' }}
        run: |
          echo "Running Checkstyle for Java"
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew checkstyleMain || true
          else
            echo "Gradle wrapper not found. Skipping Java linter."
          fi
        continue-on-error: true
