name: "PHP CI Pipeline"

on:
  workflow_call:
    inputs:
      php-version:
        description: 'La versión de PHP para usar en este pipeline'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit

  notify:
    uses: ./.github/workflows/reusable/shared-methods.yml#send-notification