name: "Python - CI Pipeline"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'La versión de Python para usar en este pipeline'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  notify:
    uses: ./.github/workflows/shared-methods.yml#send-notification