name: "Ruby CI Pipeline"

on:
  workflow_call:
    inputs:
      ruby-version:
        description: 'La versión de Ruby para usar en este pipeline'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

  notify:
    uses: ./.github/workflows/reusable/shared-methods.yml#send-notification