name: "Simulate CI Workflow Validation"

on:
  workflow_dispatch:

jobs:
  validate-yml-files:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate YAML files
        run: |
          for file in .github/workflows/*.yml; do
            echo "Validating $file"
            act --job $(basename $file .yml)
          done
