name: "Simulate CI Pipeline"

on:
  workflow_call:
    inputs:
      simulate-message:
        description: 'Mensaje para simular las etapas del pipeline'
        required: true
        type: string
      language:
        description: 'El lenguaje del proyecto'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Simulación de instalación de dependencias
      - name: Simulate Install
        run: |
          echo "${{ inputs.simulate-message }}: Instalación de dependencias simulada para ${{ inputs.language }}."

      # Simulación de ejecución de tests
      - name: Simulate Test
        run: |
          echo "${{ inputs.simulate-message }}: Ejecución de tests simulada para ${{ inputs.language }}."

      # Simulación de verificación de versión específica para cada lenguaje
      - name: Simulate Display Version
        run: |
          if [ "${{ inputs.language }}" == "dotnet" ]; then
            if command -v dotnet &> /dev/null; then
              dotnet --version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de .NET."
            fi
          elif [ "${{ inputs.language }}" == "go" ]; then
            if command -v go &> /dev/null; then
              go version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de Go."
            fi
          elif [ "${{ inputs.language }}" == "java" ]; then
            if command -v java &> /dev/null; then
              java -version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de Java."
            fi
          elif [ "${{ inputs.language }}" == "nodejs" ]; then
            if command -v node &> /dev/null; then
              node --version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de Node.js."
            fi
          elif [ "${{ inputs.language }}" == "php" ]; then
            if command -v php &> /dev/null; then
              php --version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de PHP."
            fi
          elif [ "${{ inputs.language }}" == "python" ]; then
            if command -v python3 &> /dev/null; then
              python3 --version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de Python."
            fi
          elif [ "${{ inputs.language }}" == "ruby" ]; then
            if command -v ruby &> /dev/null; then
              ruby --version
            else
              echo "${{ inputs.simulate-message }}: Simulación de versión de Ruby."
            fi
          else
            echo "${{ inputs.simulate-message }}: Lenguaje no soportado en esta simulación."
          fi
