name: "Simulate CI Pipeline"

on:
  workflow_call:
    inputs:
      simulate-message:
        description: 'Mensaje para simular las etapas del pipeline'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Simulación de un paso de instalación de dependencias
      - name: Simulate Install
        run: echo "${{ inputs.simulate-message }}: Instalación de dependencias simulada."

      # Simulación de ejecución de tests
      - name: Simulate Test
        run: echo "${{ inputs.simulate-message }}: Ejecución de tests simulada."

      # Verificación de la versión de Go (ejemplo)
      - name: Simulate Display Go version
        run: go version || echo "${{ inputs.simulate-message }}: Verificación de versión de Go simulada."